setwd("~/Desktop/LPOINT_BIG_COMP")
library(regbook)
library(MASS)
purchase = read.csv(file='final_purchase_data+weather.csv',header=T,fileEncoding = 'euc-kr')
affiliate = read.csv(file='affiliate_merge_data.csv',header=T)
Lpay = read.csv(file='Lpay_merge_data.csv',header=T)
colnames(purchase)
colnames(affiliate)
colnames(Lpay)
head(purchase)
fit <- lm(구매금액 ~채널구분+제휴사코드+상품코드+구매일자+구매시간+구매수량+성별+연령대+거주지대분류코드+대분류명+점포위치코드+점포위치세부코드+요일+거주_점포일치여부+평균기온+평균.상대습도+일강수량,data=purchase)
summary(fit)
fit <- lm(이용금액 ~채널구분+제휴사코드+제휴사세부코드+이용일자+이용시간+방문일자+성별+연령대+거주지대분류코드+점포위치코드+점포위치세부코드+이용_방문일치여부+요일+거주_점포일치여부+평균기온+평균_상대습도+일강수량,data=affiliate)
summary(fit)
fit <- lm(이용금액 ~채널구분+제휴사코드+이용일자+이용시간+성별+연령대+거주지대분류코드+요일+평균기온+평균.상대습도+일강수량,data=Lpay)
summary(fit)